export * from './CommonStyle';
export * from './LoginRegiesterStyle';
export * from './SwiperStyle';
export * from './SettingsStyle';
export * from './HelpScreenandFAQStyles';
export * from './TabStyles';
export * from './MusicDetailsStyle';
export * from './PaymentScreenStyle';
export * from './MusicPlayStyle';