const RouteName = {
    SPLSH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    HOME_TAB: 'Home',
    PREMIUM_TAB: 'Premium',
    MY_DAIRY_TAB: 'MydiaryTab',
    LIBRARY_TAB: 'LibararyTab',
    FAVIROUT_TAB: 'FavouriteTab',
    PROFILE_TAB: 'Profile',
    SELECT_LANGUAGE: 'TranslationScreen',
    FORGOT_PASSWORD: 'ForgotPassword',
    CHAT_SCREEN: 'Chatscreen',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICTION_SCREEN: 'NotificationScreen',
    MUSIC_DETAILS_SCREEN: 'MusicDetails',
    MUSIC_PALAY_SCREEN: 'MusicPlayScreens',
    PAYMENT_SCREEN: 'PaymentScreen',
    PAYMENT_SUCCESSFULLY: 'PaymentSuccessFully',
}
export default RouteName;