const images = {
   First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
   Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
   Loading: require('./LottieAnimation/loadinganim.json'),
   Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
   Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
   Account_created: require('./LottieAnimation/Accountcreated.json'),
   Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
   Languageanimation: require('./LottieAnimation/languageanimation.json'),
   Color_picker_image: require('./colorpicker.png'),
   Google_image: require('./googleicon.png'),
   Creditcard: require('./credit-card.png'),
   Paypal: require('./paypal.png'),
   phonepay: require('./phonepay.png'),
   Paypal: require('./paypal.png'),
   Upi: require('./googlepayupilogo.png'),
   paytem: require('./paytem.png'),
   Mobikwikimage: require('./Mobikwikimage.png'),
   UpliTwo: require('./UpliTwo.png'),
   PaymentSuccessFul: require('./paytemsuccesfull.png'),
   phonepay: require('./phonepay.png'),
   GooglePay: require('./google-pay.png'),
   GooglePay: require('./google-pay.png'),
   App_logo: require('./logo.jpg'),
   User_image_one_profile: require('./hundred.png'),
   PersonLogo: require('./person.png'),
   AniPayLogo: require('./anipaylogo.png'),
   ApplePayLogo: require('./applepay.png'),
   HomeIcon: require('./homeicon.png'),
   LibraryLogo: require('./librarylogo.png'),
   ProfileLogo: require('./profilelogo.png'),
   StreaksLogo: require('./streakslogo.png'),
   StreaksLogoActive: require('./streakslogoactive.png'),
   SearchLogo: require('./searchlogo.png'),

   //categories
   Categories_One: require('./categories/one.png'),
   Categories_Two: require('./categories/two.png'),
   Categories_Three: require('./categories/three.png'),
   Categories_Four: require('./categories/four.png'),
   Categories_Five: require('./categories/five.png'),
   Categories_Six: require('./categories/six.png'),
   Categories_Seven: require('./categories/seven.png'),
   Categories_Eight: require('./categories/eight.png'),
   Categories_Nine: require('./categories/nine.png'),
   Categories_Ten: require('./categories/ten.png'),
   Categories_Eleven: require('./categories/eleven.png'),
   

   Notification_one: require('./hundred.png'),
   Notification_two: require('./hundred.png'),
   Play_Icon_One: require('./LottieAnimation/PlayIcon.json'),
   One_Image: require('./hundred.png'),
   DownloadAnim: require('./LottieAnimation/downloadsanim.json'),

   // home first slider
   Home_Slider_One: require('./HomeSliderMinImage.png'),
   Home_Slider_Two: require('./HomeSliderMinImage.png'),
   Home_Slider_Three: require('./HomeSliderMinImage.png'),
   Home_Slider_Four: require('./HomeSliderMinImage.png'),

   // Search Tab
   Home_Slider_One_1: require('./hundred.png'),
   Home_Slider_Two_2: require('./hundred.png'),
   Home_Slider_Three_3: require('./hundred.png'),
   Home_Slider_Four_4: require('./hundred.png'),

   // home small slider
   Home_Sliders_1: require('./thirty.png'),
   Home_Sliders_2: require('./thirty.png'),
   Home_Sliders_3: require('./thirty.png'),
   Home_Sliders_4: require('./thirty.png'),
   Home_Sliders_5: require('./thirty.png'),
   Home_Sliders_6: require('./thirty.png'),
   Home_Sliders_7: require('./thirty.png'),
   Home_Sliders_8: require('./thirty.png'),
   Home_Sliders_9: require('./thirty.png'),
   Home_Sliders_10: require('./thirty.png'),

   // home second small slider
   Home_Slider_1: require('./hundred.png'),
   Home_Slider_2: require('./hundred.png'),
   Home_Slider_3: require('./hundred.png'),
   Home_Slider_31: require('./HomeSliderMinImage.png'),
   Home_Slider_4: require('./hundred.png'),
   Home_Slider_5: require('./hundred.png'),
   Home_Slider_6: require('./hundred.png'),
   Home_Slider_7: require('./hundred.png'),
   Home_Slider_8: require('./hundred.png'),
   Home_Slider_9: require('./hundred.png'),
   Home_Slider_10: require('./hundred.png'),
   Home_Slider_11: require('./hundred.png'),
   Home_Slider_12: require('./hundred.png'),
   Home_Slider_13: require('./hundred.png'),
   Home_Slider_14: require('./hundred.png'),
   Home_Slider_15: require('./hundred.png'),
   Home_Slider_17: require('./hundred.png'),
   Background_Image: require('./backgroundimage.png'),

   Apple: require('./apple.png'),

   // Musicplay Image
   MusicPlay_Image_1: require('./two_fifty.png'),
   MusicPlay_Image_2: require('./two_fifty.png'),
   MusicPlay_Image_3: require('./two_fifty.png'),
   MusicPlay_Image_4: require('./two_fifty.png'),
   MusicPlay_Image_5: require('./two_fifty.png'),


}
export default images;